INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "3/1/21", "3/31/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "10/1/20", "10/31/20");


INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);
INSERT INTO users (name, age) VALUES ("Vanessa Fiechtner", 27);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
